version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pipeline-postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: analytics_db

    ports:
      - "5433:5432"

    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql

    networks:
      - my-network

  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db

    ports:
      - "8000:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      # 將本地 ./api-request 映射到容器裡的 /opt/airflow/api-request 路徑
      - ./api-request:/opt/airflow/api-request
    networks:
      - my-network

    command: >
      bash -c "airflow db migrate && airflow standalone"


  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    platform: linux/amd64
    volumes:
      - ./dbt/de_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - postgres
    networks:
      - my-network
    command: run
    # command: debug
    # command: init de_project

networks:
  my-network:
    driver: bridge
